name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Python Setup
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Deploy to AWS Lambda
      run: |
        python -m pip install --upgrade pip
        pip install awscli
        # pip install -r requirements.txt -t .
        # cd app && zip -r lambda_function.zip .
        zip -r lambda_function.zip .
        aws lambda update-function-code --function-name ${{ secrets.FUNCTION_NAME }} --zip-file fileb://lambda_function.zip --publish
